/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-surface-variant": "#44474e",
        "surface-container": "#eceef0",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#041a3d",
        background: "#f7f9fb",
        "secondary-fixed": "#ecdcff",
        primary: "#000000",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#d5baff",
        "surface-bright": "#f7f9fb",
        "on-secondary-fixed-variant": "#5e00c1",
        surface: "#f7f9fb",
        "tertiary-container": "#00201a",
        "on-primary-container": "#7184ac",
        "on-tertiary-container": "#009580",
        "outline-variant": "#c5c6cf",
        "on-tertiary-fixed-variant": "#005144",
        "secondary-container": "#8e42fd",
        "primary-fixed": "#d8e2ff",
        "surface-container-high": "#e6e8ea",
        outline: "#75777f",
        "primary-fixed-dim": "#b4c6f2",
        "tertiary-fixed": "#26fedc",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#270057",
        secondary: "#751be3",
        "surface-container-highest": "#e0e3e5",
        "inverse-on-surface": "#eff1f3",
        "tertiary-fixed-dim": "#00dfc1",
        "surface-tint": "#4c5e85",
        "surface-container-low": "#f2f4f6",
        "on-secondary-container": "#fdf6ff",
        "primary-container": "#041a3d",
        "on-primary-fixed-variant": "#34466b",
        "surface-variant": "#e0e3e5",
        "inverse-surface": "#2d3133",
        error: "#ba1a1a",
        "on-error-container": "#93000a",
        "inverse-primary": "#b4c6f2",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        tertiary: "#000000",
        "on-tertiary-fixed": "#00201a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xl: "80px",
        md: "24px",
        base: "8px",
        "margin-desktop": "64px",
        sm: "12px",
        lg: "48px",
        "margin-mobile": "16px",
        xs: "4px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg": ["Anybody"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg": ["Anybody"],
        "label-caps": ["JetBrains Mono"],
        "title-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Anybody"],
        "body-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "display-lg": [
          "72px",
          {
            lineHeight: "76px",
            letterSpacing: "-0.02em",
            fontWeight: "800",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "16px",
            letterSpacing: "0.1em",
            fontWeight: "500",
          },
        ],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "38px", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
